### ISSUE TITLE
logo contribution

### ISSUE THREAD

**Issue by reallinfo** [lucasvmiguel/kv-store#1]
Hi @lucasvmiguel , i am a logo designer. I contribute to open source projects that do not have logo. I designed a logo that represents the software function and name. Also, The idea of ​​logo is available in the following image. What do you think? I will wait for feedback. Have a nice day!

![KV](https://user-images.githubusercontent.com/36298335/56380716-97af5500-621b-11e9-9d42-31fd51e653bf.jpg)

Readme file view;

![kv2](https://user-images.githubusercontent.com/36298335/56380733-9f6ef980-621b-11e9-9970-3d4a47e346f3.png)

**Comment by lucasvmiguel** [comment]
Hi, 

Really awesome, I was not thinking about creating a logo, but I'm glad that you made it.

What can I do for your kind contribution?

**Comment by reallinfo** [comment]
I'm glad you like it :)  Thank you very much, but you don't have to do anything. Do you want to make any changes to the logo? color etc... I will send you a PR.

**Comment by lucasvmiguel** [comment]
No, you don't need to change anything, I loved it... Share with me your LinkedIn, maybe we can work on future projects together =)

**Comment by reallinfo** [comment]
Unfortunately I don't use linkedin. But you can reach me at any time through github. and my mail address: komiserback@gmail.com 

Feel free to write when you need about the logo. Have a nice day!
